### PR TITLE
Add port argument

### PR DESCRIPTION
**Pull request by kozzztya**
I added port argument according to these discussions https://github.com/feathersjs/feathers-socketio/pull/66
Please check.

Closes https://github.com/feathersjs/feathers-docs/issues/461

### CODE REVIEW

**Comment by daffl** [comment]
That looks great, thank you! Could you create another PR that adds the appropriate documentation below https://docs.feathersjs.com/api/socketio.html#appconfiguresocketiooptions--callback ? Then we can merge and release.

**Comment by kozzztya** [comment]
@daffl Okay, I've added information about the port argument.
https://github.com/feathersjs/feathers-docs/pull/527

**Comment by daffl** [comment]
Awesome, thank you! Released as v1.6.0 and documentation has been published as well.

**Comment by ekryski** [comment]
Nice @kozzztya! Thanks for all the great PRs! 😄

**Comment by kozzztya** [comment]
You're welcome.

**Pull request merged**
